#!/opt/nutwatch/venv/bin/python3
import sys

sys.path.insert(0, "/opt/nutwatch")
from services.wol import dispatch

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(1)
    upsname, event = sys.argv[1], sys.argv[2]
    dispatch(upsname, event)